logger:
  console:
    level: DEBUG
    enableColors: true
    includeEntities: true
    prettyEntities: true
  file:
    level: DEBUG
    enabled: true
    dir: ./app-logs
    includeEntities: true
    prettyEntities: false